name: Check for Broken Links

on:
  push:
    branches:
      - master

env:
  URL: https://weaversa.github.io/cryptol-course
  CONFIG: .github/workflows/hydra-config.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
